#CI de nivel 03 - Disparo automatico sempre que outro for concluído, como exemplo um deploy

# nome que vai aparecer la nas opções de pipe 
name: 'Execução por Deploy'

# regras de disparo da execucao (Triggers OU gatilhos de execução)
  #gatilhos de exec após outro workflow = workflow_run
on: 
  workflow_run: 
    workflows: [ 'Execução Manual' ]
    types: 
      - completed
    

jobs: 

  # descrição do job 
  e2e-tests: 

    #maquina que o job vai executar 
    runs-on: ['ubuntu-latest']

    #passo a passo das acoes do job 
    steps: 

      - uses: actions/checkout@v4

      #- uses: actions/setup-node@v4
      #  with: 
      #    node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências 
        run: yarn

      - name: Instalando Playwright 
        run: yarn playwright install 

      - name: Testes E2E (end-to-end) 
        run: yarn run e2e

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancellad() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report



